apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels: 
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15.2
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: kubenews_bd
          - name: POSTGRES_USER
            value: kubenews
          - name: POSTGRES_PASSWORD
            value: kubenews
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - port: 5432
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels: 
        app: web
    spec:
      containers:
        - name: web
          image: andore14/kube-news:v2
          ports:
          - containerPort: 8080
          env:
          - name: DB_HOST
            value: postgresql
          - name: DB_DATABASE
            value: kubenews_bd
          - name: DB_USERNAME
            value: kubenews
          - name: DB_PASSWORD
            value: kubenews
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort